@echo off
echo Starting Backend...
start "Backend" cmd /k "cd backend && venv\Scripts\activate && uvicorn app.main:app --reload"

echo Starting Frontend...
start "Frontend" cmd /k "cd frontend && npm run dev"

echo Application starting...
